# Generated by Django 2.1 on 2018-08-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20180817_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='detailmedicalaid',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required medical assistance - ആവശ്യമായ മെഡിക്കൽ സഹായത്തിനായുള്ള വിശദാംശങ്ങൾ'),
        ),
        migrations.AddField(
            model_name='request',
            name='needmedicalaid',
            field=models.BooleanField(default='previously unasked, left empty', verbose_name='Medical Aid - ഡോക്ടർമാർ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ngo',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestee_phone',
            field=models.CharField(max_length=12, verbose_name='Requestee Phone - അപേക്ഷകന്\u200dറെ ഫോണ്\u200d നമ്പര്\u200d'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
